### ISSUE TITLE
Blockers to BIPM SI Brochure publication

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#169]
This is a follow up to #127.

From @manuel489 :

* [x] French references don't fetch when a tilde is present in the identifier. E.g. " Résolution", " Réunion", " Déclaration", etc. (https://github.com/relaton/relaton-bipm/issues/27)
* [x] This issue: https://github.com/metanorma/bipm-data-outcomes/issues/11, hasn't been fixed and it's generating fetching errors. Maybe I could fix it manually?
* [x] #172 (Meeting references are not being hidden and they don't contain any link to an external source, even when this link is present in the YAML file from relaton-data-bipm repository.)
* [x] Hand-crafted references are not being hidden and the hyperlink provided is not being used in the cross-reference. In other words, it is working as an usual cross-reference.
* [x] I haven't been able to compile French version document in its entirety. Need to perform a deeper investigation.

**Comment by ronaldtse** [comment]
From @opoudjis :

1. I had already also said what the solution I had already implemented is: I was overwriting the English with the French word
3. aren't going to be hidden unless I'm told to hide them, and they're news to me. I would assume this to be a metanorma issue
4. Are the references in 4 being marked up as hidden?

**Comment by ronaldtse** [comment]
Issue 1 is posted here: https://github.com/relaton/relaton-bipm/issues/27

> 3: aren't going to be hidden unless I'm told to hide them, and they're news to me. I would assume this to be a metanorma issue

@manuel489 please help explain. Metanorma is not meant to automatically hide these references unless explicitly requested to.

> 4. Hand-crafted references are not being hidden and the hyperlink provided is not being used in the cross-reference. In other words, it is working as an usual cross-reference.

I don't understand this either. Are these AsciiBib items? What would you expect to see? Do you want these to be hidden? And do you want this to link to the webpage within the inline reference?

**Comment by manuel489** [comment]
> @manuel489 please help explain. Metanorma is not meant to automatically hide these references unless explicitly requested to.

@ronaldtse taking as an example this "old" reference from original source: **(CR, 54)**

![capture1](https://user-images.githubusercontent.com/33627611/172630118-40343707-3006-4a4a-83a9-e6d17e0ab069.PNG)


This one corresponds to page 54 of the Meeting 9th.
Which in Metanorma is encoded as:
````
* [[[CR1948, CGPM Meeting 9]]]
````
and it renders:
![capture2](https://user-images.githubusercontent.com/33627611/172630830-bf3c84a0-8259-4529-8b51-695fc4c93167.PNG)

The cross-reference renders:
![capture3](https://user-images.githubusercontent.com/33627611/172631368-d7d926c2-3102-4767-b872-db66969c4b6d.PNG)

and when it's clicked, it leads to the reference in bibliography instead to the corresponding external source.

Now, I'm not sure wether these type of references are meant to be automatically hidden.

**Comment by manuel489** [comment]
> I don't understand this either. Are these AsciiBib items? What would you expect to see? Do you want these to be hidden? And do you want this to link to the webpage within the inline reference?

This matter has been discussed in private and concurred on hiding these references manually.

**Comment by manuel489** [comment]
>  I haven't been able to compile French version document in its entirety. Need to perform a deeper investigation.

A ticket was raised for this one.

**Comment by ronaldtse** [comment]
> I haven't been able to compile French version document in its entirety. Need to perform a deeper investigation.

I've been able to do this without problem, closing this particular topic.

**Comment by ronaldtse** [comment]
> Meeting references are not being hidden and they don't contain any link to an external source, even when this link is present in the YAML file from relaton-data-bipm repository

The meeting references are still not hidden and are not linked:
<img width="561" alt="Screenshot 2022-06-20 at 5 40 09 PM" src="https://user-images.githubusercontent.com/11865/174561451-2f28712c-c702-4bea-ae37-e09e1b92b298.png">

**Comment by opoudjis** [comment]
By my reckoning the only remaining issues are:

* https://github.com/metanorma/metanorma-bipm/issues/175 = https://github.com/relaton/relaton-bipm/issues/27

Could @manuelfuenmayor or @ronaldtse confirm?

**Comment by manuelfuenmayor** [comment]
@opoudjis, yes.

**Comment by ronaldtse** [comment]
Correct. And we've requested BIPM to enter the meetings that were missing from their site and they've done it too. The automatic fetching of those entries are now pending on https://github.com/metanorma/bipm-data-outcomes/issues/13 and a re-run of Relaton-BIPM.

**Comment by ronaldtse** [comment]
Confirm that the remaining issue is fixed:
> French references don't fetch when a tilde is present in the identifier. E.g. " Résolution", " Réunion", " Déclaration", etc. 

Thank you everyone!

**Comment by opoudjis** [comment]
Nooooot so faast. This is only working because of my "hack", so called, of replacing English words with French in Presentation XML cross-references: it isn't the official fix of selecting on the French version of the identifier. This is not a blocker, so I'm keeping this issue closed, but I'm reopening https://github.com/metanorma/metanorma-bipm/issues/175
